### PR TITLE
use raster::predict, implement multi-core processing for rasters

### PR DESCRIPTION
**Pull request by dnbucklin**
This implements multi-core processing for raster prediction and thresholding. The originally sourced script 
`RasterPredictMod.R` is also no longer needed due to native handling of RF models by `raster::predict`.

Make sure to update/install necessary packages for this update:
```
install.packages(c("snow","raster"))
```

### CODE REVIEW

**Comment by tghoward** [comment]
Thanks!

**Comment by tghoward** [comment]
@dnbucklin it looks like writeRaster is only in the try block for the cluster, but not the other try blocks. So writeRaster won't happen if there's no parallel.  Was that intentional?

**Comment by dnbucklin** [comment]
@tghoward It is coded inconsistently, but the `writeRaster` call isn't needed for the non-cluster cases, since the `writeRaster` arguments are specified directly in the `predict()` call:

```
outRas <- predict(object=envStack, model=rf.full, type = "prob", index=2,
                    filename=fileNm, format = "GTiff", overwrite=TRUE)
```

I must not have known at the time, but I could have put the `writeRaster` arguments in the `clusterR` call.

**Comment by tghoward** [comment]
Ah! right, of course. I knew that but of course didn't remember this morning after merging and using it in another project.  Thanks for clarifying.

**Pull request merged**
