### PR TITLE
map based on ggplot

### PR DESCRIPTION
**Pull request by ChristopherTracey**
test implementatin of the map for the metadata bases on ggplot

### CODE REVIEW

**Comment by tghoward** [comment]
@ChristopherTracey yes, there seem to be some problems. It has a bunch of my most recent changes as part of your PR. I think that might be the reason it says there are merge conflicts. How did you bring in those most recent changes of mine? `git pull` should have done the trick.

**Comment by tghoward** [comment]
How about using the ggplot wrapper in rasterVis (it subsamples):
https://cran.r-project.org/web/packages/rasterVis/index.html

**Comment by ChristopherTracey** [comment]
Hmm. Did not know about that package. I will investigate.

On Oct 11, 2016, at 9:46 AM, Tim Howard <notifications@github.com<mailto:notifications@github.com>> wrote:

How about using the ggplot wrapper in rasterVis (it subsamples):
https://cran.r-project.org/web/packages/rasterVis/index.html

##

**Comment by ChristopherTracey** [comment]
I think what happened to the pull request is that I was a version or two behind the master and when I synced it up (via GitHub desktop), it somehow added in the conflicts. Admittedly, I think I may have copy and pasted updated code from you into my local file--mostly because I didn't want to update all the paths.  _Maybe I'm not great of a GitHub user... ;)_

So regarding this path issue, how should we handle this as this modeling group? We all likely to have different paths and filenames for the species data? Do we want to sync these back to the master with a potentially different and confusing set of paths and file names?

**Comment by tghoward** [comment]
If we handle it correctly, the path issue is a non-issue; git can handle it. For someone making tweaks and doing PRs, (you) this is a good way to do it: Make a branch of the master (call it "PA" or something). Switch to this branch and make your various PA-specific tweaks (such as paths). For anything you want to push back to the group, make those changes in the master branch instead. 

After making a change in the master, push it up to your github site for the PR. Also switch back to the PA branch and pull the change in. Any other changes anyone has made to the main repository, you bring down locally to the master branch, but then simply merge to your modified branch with a `git merge`. This way you keep your paths and other customizations on the PA branch and they never get overwritten.  I guess I should go over that on Thursday.

**Comment by ChristopherTracey** [comment]
Yeah, this makes a lot more sense. I'll fix what I did

**Pull request closed without merging**
